# Generated by Django 4.0.10 on 2024-03-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_user_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='coverPhoto',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='creator',
            name='profilePhoto',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
