# Generated by Django 4.0.10 on 2024-03-13 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_creator_coverphoto_alter_creator_profilephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='walletAddress',
            field=models.CharField(blank=True, max_length=42, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Wallet Address'),
        ),
        migrations.AlterField(
            model_name='creator',
            name='walletAddress',
            field=models.CharField(blank=True, max_length=42, unique=True, validators=[django.core.validators.RegexValidator(regex='^0x[a-fA-F0-9]{40}$')], verbose_name='Wallet Address'),
        ),
    ]
