# Generated by Django 4.0.10 on 2024-04-01 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_account_walletaddress_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterField(
            model_name='creator',
            name='price',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='creatorpost',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='api.creator'),
        ),
    ]
