# Generated by Django 4.0.10 on 2024-04-17 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_account_options_alter_creator_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creator',
            name='user',
        ),
    ]
