# Generated by Django 4.0.10 on 2024-04-17 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_account_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='subscribed',
        ),
    ]
