# Generated by Django 4.0.10 on 2024-04-24 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_account_subscriptions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='subscribers', to='api.account'),
        ),
    ]
