# Generated by Django 4.0.10 on 2024-04-27 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_account_user_alter_creator_user_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.account')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creator')),
            ],
            options={
                'unique_together': {('account', 'creator')},
            },
        ),
    ]
