# Generated by Django 4.0.10 on 2024-05-08 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_subscription_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nickName',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=30),
        ),
        migrations.AlterField(
            model_name='creator',
            name='nickName',
            field=models.CharField(default=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=30),
        ),
    ]
