# Generated by Django 4.0.10 on 2024-05-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_account_nickname_alter_creator_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='nickName',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='creator',
            name='nickName',
            field=models.CharField(max_length=30),
        ),
    ]
